name: Tasmania
favicon: null
layout_spectrum: 0.70863
typography_spectrum: 0.9345182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000201'
    - '#fbffff'
    - '#a7e3ff'
    - '#76b1e9'
    - '#4572ad'
  brandStrength: 0.7174432
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
